apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: kafka-to-s3
spec:
  flows:
    - route:
        from:
          uri: kamelet:kafka-source
          steps:
            - log:
                message: ${body}
            - to:
                uri: aws2-s3://arn:aws:s3:::unityteste/events/
                parameters:
                  region: us-east-1
                  trustAllCertificates: true
                  operation: copyObject
                  accessKey: A
                  secretKey: B
          parameters:
            topic: events
            bootstrapServers: localhost:55001
            user: user
            password: pass
