{
 "title": "One Tap Soccer",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Games",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(com_redhat_onetapsoccer_game_start_total)"
    }
   ]
  },
  {
   "title": "Game Over",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(com_redhat_onetapsoccer_game_over_total)"
    }
   ]
  },
  {
   "title": "Shoots",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(com_redhat_onetapsoccer_shoot_total)"
    }
   ]
  },
  {
   "title": "Goals",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(com_redhat_onetapsoccer_goal_total)"
    }
   ]
  },
  {
   "title": "Events Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(com_redhat_onetapsoccer_total)"
    }
   ]
  },
  {
   "title": "Unique Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count by (user) (com_redhat_onetapsoccer_game_start_total))"
    }
   ]
  },
  {
   "title": "Head Collision",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(com_redhat_onetapsoccer_head_collision_total)"
    }
   ]
  },
  {
   "title": "Ground Collision",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(com_redhat_onetapsoccer_ground_collision_total)"
    }
   ]
  },
  {
   "title": "Pole Collision",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(com_redhat_onetapsoccer_pole_collision_total)"
    }
   ]
  },
  {
   "title": "Collisions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(com_redhat_onetapsoccer_pole_collision_total) + sum(com_redhat_onetapsoccer_head_collision_total) + sum(com_redhat_onetapsoccer_ground_collision_total)"
    }
   ]
  },
  {
   "title": "Total Events",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (kind) (com_redhat_onetapsoccer_total)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Goals per Player",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (player) (com_redhat_onetapsoccer_total{kind=\"goal\"})",
     "legendFormat": "{{player}}"
    }
   ]
  }
 ]
}